#version: '3.9'
#
#services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./app:/app
#    environment:
#      - FLASK_ENV=production
#    command: ["python", "MainGame.py"]

version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./Scores/Scores.txt:/app/Scores.txt